const content=document.querySelector('#page-content');
const title=document.querySelector('#page-title');
const subtitle=document.querySelector('#page-subtitle');
const period=document.querySelector('#period-button');

const materialRows=[
['MSP','Arsitektur & Interior',100,1,1,'Perlu percepatan'],
['MSP','MEP',62,6,6,'On track with alert'],
['GBI','MEP',104,12,4,'On track with alert'],
['Taman Milenial','Arsitektur',40,16,16,'On track'],
['Taman Milenial','Struktur',19,5,5,'On track'],
['Taman Milenial','MEP',20,2,2,'Perlu percepatan']
];
const longLead=['Marble','Ceiling Metal','Veneer','Custom Hanging Lamp','Artwork','Labradorite','HPL','Roller Blind','Loose Furniture','ACP','Curve Glass','Outdoor Nest','AHU','Videotron','Audio Video','Special Lighting','ETFE'];
const shopPlan=[
['MSP','Arsitektur & Interior','Pendetailan Shop Drawing dan RKS teknis','5 Agustus 2026','Quadratura / JKON / CCM','Workshop'],
['MSP','MEP','Koordinasi pembongkaran plafon dan MEP existing','Minggu ke-3','JKON / CCM','Prioritas'],
['Taman Milenial','Struktur & Arsitektur','Pendetailan Shop Drawing dan RKS teknis','6 Agustus 2026','Quadratura / JKON / CCM','Workshop'],
['Taman Milenial','MEP','Koordinasi lintas disiplin','Minggu ke-5','JKON / CCM','On track with alert'],
['GBI','MEP, AV & Interior','Pendetailan Shop Drawing dan RKS teknis','6–7 Agustus 2026','Metrik / JKON / CCM','Workshop'],
['Semua Area','Final report','Laporan Design Workshop Shop Drawing','7 Agustus 2026 malam','Seluruh pihak','Deliverable']
];

function setNav(route){document.querySelectorAll('#main-nav a').forEach(a=>a.classList.toggle('active',a.dataset.route===route));}
function routeTo(name){location.hash=name;}
function barRows(rows){return rows.map(([n,v])=>`<div class="barrow"><span>${n}</span><div class="track"><i style="width:${v}%"></i></div><b>${v}%</b></div>`).join('');}
function materialChart(){return materialRows.map(([a,d,t,s,ap])=>`<div class="col"><div class="stack"><i class="submitted" style="height:${Math.max(4,s/t*160)}px"></i><i class="approved" style="height:${Math.max(4,ap/t*160)}px"></i></div><span>${a==='Taman Milenial'?'Tamil':a} ${d.split(' ')[0]}</span></div>`).join('');}
function lineChart(){setTimeout(()=>{const svg=document.querySelector('#line-chart');if(!svg)return;const plan=[.1152,.2365,.52,.9,1.4,2.1,2.9,3.8],actual=[.1152],W=760,H=260,p=40,max=4,x=i=>p+i*(W-2*p)/(plan.length-1),y=v=>H-p-v/max*(H-2*p);let out=`<line class="axis" x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}"/><line class="axis" x1="${p}" y1="${p}" x2="${p}" y2="${H-p}"/>`;for(let i=0;i<plan.length;i++)out+=`<text class="tick" x="${x(i)}" y="${H-16}" text-anchor="middle">M-${i+1}</text>`;for(let v=0;v<=4;v++)out+=`<text class="tick" x="10" y="${y(v)+4}">${v}%</text><line class="axis" x1="${p}" y1="${y(v)}" x2="${W-p}" y2="${y(v)}" opacity=".35"/>`;const path=a=>a.map((v,i)=>(i?'L':'M')+x(i)+','+y(v)).join(' ');out+=`<path class="plan" d="${path(plan)}"/>${plan.map((v,i)=>`<circle class="dot" cx="${x(i)}" cy="${y(v)}" r="4"/>`).join('')}<path class="actual" d="${path(actual)}"/>${actual.map((v,i)=>`<circle class="dot actual" cx="${x(i)}" cy="${y(v)}" r="4"/>`).join('')}`;svg.innerHTML=out;},0);}

function overview(){title.textContent='Project Dashboard';subtitle.textContent='Lobby MSP, GBI & Taman Milenial · Update 04 Agustus 2026 (M-2)';period.textContent='29 Jul–04 Agu 2026';content.innerHTML=`
<section class="stats"><article><small>Kumulatif rencana</small><strong>0,2365%</strong><span>Minggu ke-2</span></article><article><small>Realisasi M-2</small><strong>Belum tersedia</strong><span>Belum diisi pada laporan sumber</span></article><article><small>Status proyek</small><strong>On Track</strong><span class="warn">With Alert</span></article><article><small>Shop drawing</small><strong>5,9%</strong><span>Target selesai minggu ke-5</span></article><article><small>Material approved</small><strong>10,2%</strong><span>34 dari 333 item</span></article></section>
<section class="grid3"><article class="panel clickable" onclick="routeTo('shopdrawing')"><h2>1. Engineering & Shop Drawing</h2><p>Klik untuk membuka perencanaan detail per area dan deliverable</p><div class="ring"><div><b>5,9%</b><span>shop drawing</span></div></div>${barRows([['Shop Drawing',5.9],['Material Approval',10.2],['Metode/JSA',0]])}</article><article class="panel clickable" onclick="routeTo('material')"><h2>2. Material & Long Lead</h2><p>Klik untuk membuka register per area dan daftar material kritis</p><div class="columns">${materialChart()}</div><div class="triple"><div><b>333</b><span>Total item</span></div><div><b>34</b><span>Approved</span></div><div><b>${longLead.length}</b><span>Long lead</span></div></div></article><article class="panel clickable" onclick="routeTo('bim')"><h2>3. BIM Coordination</h2><p>Klik untuk membuka milestone, clash reporting dan kebutuhan data</p><div class="source-note">Clash detection wajib dilaporkan setiap minggu. Angka clash aktual belum tersedia, sehingga dashboard tidak lagi menampilkan angka contoh.</div><div class="bimfoot"><div><b>LOD 350</b><span>Basis awal komitmen tender</span></div><div><b>Revit 2026</b><span>Versi kerja yang diarahkan</span></div></div></article></section>
<section class="grid2"><article class="panel"><h2>Rencana vs Realisasi Kumulatif</h2><p>Realisasi M-2 belum tersedia pada laporan sumber</p><svg id="line-chart" viewBox="0 0 760 260"></svg></article><article class="panel clickable" onclick="routeTo('workshop')"><h2>Design Workshop 5–8 Agustus</h2><p>Dua ruang kerja paralel: shop drawing/RKS dan approval material/long lead</p><div class="actions"><div><b>05</b><p><strong>MSP</strong>Pendetailan shop drawing, RKS, material dan long lead.</p><em>Agustus</em></div><div><b>06</b><p><strong>Taman Milenial & GBI</strong>Sesi area dan disiplin secara bertahap.</p><em>Agustus</em></div><div><b>07</b><p><strong>GBI & laporan akhir</strong>Presentasi hasil workshop kedua jalur.</p><em>Agustus</em></div></div></article></section>`;lineChart();}

function shopdrawing(){title.textContent='Perencanaan Shop Drawing';subtitle.textContent='Detail engineering plan per area, disiplin, target dan deliverable';period.textContent='Target utama: Minggu ke-5';content.innerHTML=`<div class="detail-head"><div><h2>Shop Drawing Planning Register</h2><p>Halaman ini dibuka dari kartu Shop Drawing pada dashboard utama.</p></div><button class="ghost" onclick="routeTo('overview')">← Kembali</button></div><section class="detail-kpis"><article class="mini-card"><span>Progress laporan M-2</span><strong>5,9%</strong></article><article class="mini-card"><span>Target penyelesaian</span><strong>Minggu ke-5</strong></article><article class="mini-card"><span>Fokus workshop</span><strong>3 area</strong></article><article class="mini-card"><span>Status</span><strong class="warn">With Alert</strong></article></section><div class="tabs"><button class="active">Master Plan</button><button onclick="filterShop('MSP',this)">MSP</button><button onclick="filterShop('Taman Milenial',this)">Taman Milenial</button><button onclick="filterShop('GBI',this)">GBI</button></div><div class="table-wrap"><table><thead><tr><th>Area</th><th>Disiplin/Paket</th><th>Rencana kegiatan</th><th>Target</th><th>Pihak terkait</th><th>Status</th></tr></thead><tbody id="shop-table">${shopRows(shopPlan)}</tbody></table></div><section class="grid2"><article class="panel"><h2>Deliverable minimum</h2><div class="actions"><div><b>01</b><p><strong>General arrangement</strong>Denah existing, demolition, proposed dan setting out.</p><em>Plan</em></div><div><b>02</b><p><strong>Koordinasi teknis</strong>Potongan, detail sambungan, MEP coordination dan BIM view.</p><em>Detail</em></div><div><b>03</b><p><strong>Construction release</strong>Revisi, approval, metode kerja, JSA dan referensi material.</p><em>Issue</em></div></div></article><article class="panel"><h2>Gate perencanaan</h2><div class="timeline"><article><time>Gate 1</time><div><h3>Kelengkapan dasar desain</h3><p>RKS, gambar tender, survey existing dan keputusan rapat tersedia.</p></div></article><article><time>Gate 2</time><div><h3>Koordinasi lintas disiplin</h3><p>Clash, konstruktabilitas, sequence dan akses pekerjaan diperiksa.</p></div></article><article><time>Gate 3</time><div><h3>Approval dan release</h3><p>Gambar disetujui sebelum material dan pekerjaan dilepas ke lapangan.</p></div></article></div></article></section><div class="source-note">Daftar ini disusun dari arah Laporan Mingguan M-2 dan rundown Design Workshop. Nomor gambar individual belum tersedia pada dokumen yang diterima, sehingga tidak diisi secara asumtif.</div>`;}
function shopRows(rows){return rows.map(r=>`<tr>${r.slice(0,5).map(x=>`<td>${x}</td>`).join('')}<td><span class="status ${r[5]==='Prioritas'?'alert':r[5]==='Deliverable'?'done':''}">${r[5]}</span></td></tr>`).join('');}
window.filterShop=(area,btn)=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#shop-table').innerHTML=shopRows(shopPlan.filter(r=>r[0]===area));};

function material(){title.textContent='Material & Long Lead';subtitle.textContent='Detail approval material per area dan daftar item kritis';period.textContent='Target workshop: 5–7 Agu';content.innerHTML=`<div class="detail-head"><div><h2>Material Approval Register</h2><p>Angka mengikuti rekap yang telah dicatat pada Laporan Mingguan M-2.</p></div><button class="ghost" onclick="routeTo('overview')">← Kembali</button></div><section class="detail-kpis"><article class="mini-card"><span>Total item</span><strong>333</strong></article><article class="mini-card"><span>Submitted</span><strong>42</strong></article><article class="mini-card"><span>Approved</span><strong>34</strong></article><article class="mini-card"><span>Approval rate</span><strong>10,2%</strong></article></section><div class="table-wrap"><table><thead><tr><th>Area</th><th>Disiplin</th><th>Total</th><th>Submitted</th><th>Approved</th><th>Status</th></tr></thead><tbody>${materialRows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td>${r[3]}</td><td>${r[4]}</td><td><span class="status ${r[5].includes('Perlu')?'alert':'done'}">${r[5]}</span></td></tr>`).join('')}</tbody></table></div><section class="panel" style="margin-top:14px"><h2>Long Lead Item</h2><p>Material yang telah disebut dalam monitoring proyek; status individual PO/kedatangan belum tersedia.</p><div class="actions">${longLead.map((x,i)=>`<div><b>${String(i+1).padStart(2,'0')}</b><p><strong>${x}</strong>Status detail supplier, approval, PO dan ETA perlu dihubungkan ke procurement register.</p><em>Open</em></div>`).join('')}</div></section>`;}

function bim(){title.textContent='BIM Coordination';subtitle.textContent='Milestone, weekly clash reporting, 5D, 7D dan data exchange';period.textContent='Revit 2026';content.innerHTML=`<div class="detail-head"><div><h2>BIM Delivery Plan</h2><p>Halaman detail berdasarkan risalah Kick Off BIM dan komitmen tender.</p></div><button class="ghost" onclick="routeTo('overview')">← Kembali</button></div><section class="detail-kpis"><article class="mini-card"><span>Basis model awal</span><strong>LOD 350</strong></article><article class="mini-card"><span>Target as-built</span><strong>LOD 500</strong></article><article class="mini-card"><span>Clash reporting</span><strong>Mingguan</strong></article><article class="mini-card"><span>Platform</span><strong>ACC / CDE</strong></article></section><section class="grid2"><article class="panel"><h2>Milestone BIM</h2><div class="timeline"><article><time>01</time><div><h3>Existing & preparation model</h3><p>Survey existing, pagar, tunnel, sirkulasi, scaffolding dan pekerjaan persiapan divisualisasikan.</p></div></article><article><time>02</time><div><h3>Coordinated shop drawing model</h3><p>Federasi arsitektur, struktur, MEP dan temporary works; clash dilaporkan setiap minggu.</p></div></article><article><time>03</time><div><h3>4D dan 5D</h3><p>Model dikaitkan dengan sequence; 5D digunakan sebagai pembanding terhadap RAB.</p></div></article><article><time>04</time><div><h3>As-built dan 7D</h3><p>Parameter aset dibuat sejak awal dan dilengkapi pada model as-built.</p></div></article></div></article><article class="panel"><h2>Data exchange</h2><div class="actions">${['RVT – authoring Revit 2026','IFC – interoperabilitas BIM','NWC/NWD – koordinasi Navisworks','DWG/PDF – dokumen gambar','SKP – model SketchUp sebagai exchange','AR – visualisasi lapangan/presentasi'].map((x,i)=>`<div><b>${i+1}</b><p><strong>${x}</strong>Standar naming, versi dan status penerbitan perlu dikontrol melalui BEP/CDE.</p><em>Req.</em></div>`).join('')}</div></article></section><div class="source-note">Angka hard clash, soft clash dan resolved belum tersedia pada dokumen sumber. Grafik dummy sebelumnya telah dihapus agar dashboard tidak menampilkan data yang seolah-olah aktual.</div>`;}

function workshop(){title.textContent='Design Workshop Tracker';subtitle.textContent='Rapat koordinasi luar kantor, 5–8 Agustus 2026';period.textContent='Hotel di Jakarta';content.innerHTML=`<div class="detail-head"><div><h2>Workshop Schedule & Deliverables</h2><p>Dua jalur paralel: Meeting Room 1 untuk shop drawing/RKS dan Meeting Room 2 untuk material/long lead.</p></div><button class="ghost" onclick="routeTo('overview')">← Kembali</button></div><section class="detail-kpis"><article class="mini-card"><span>Pelaksanaan</span><strong>5–8 Agu</strong></article><article class="mini-card"><span>Ruang paralel</span><strong>2</strong></article><article class="mini-card"><span>Area bahasan</span><strong>MSP, Tamil, GBI</strong></article><article class="mini-card"><span>Output akhir</span><strong>2 laporan</strong></article></section><div class="timeline"><article><time>5 Agustus</time><div><h3>Hari 1 — MSP</h3><p>Pembukaan, rencana deliverable, pendetailan shop drawing/RKS, approval material dan long lead. Terdapat rapat koordinasi eksekutif pukul 13.30–15.30.</p></div></article><article><time>6 Agustus</time><div><h3>Hari 2 — Taman Milenial lalu GBI</h3><p>Pagi hingga sore fokus Taman Milenial; sesi GBI dimulai pukul 15.45 dan berlanjut malam.</p></div></article><article><time>7 Agustus</time><div><h3>Hari 3 — GBI dan laporan hasil</h3><p>GBI dibahas penuh. Pukul 19.30–selesai: laporan Design Workshop Shop Drawing dan laporan Approval Material.</p></div></article><article><time>8 Agustus</time><div><h3>Checkout</h3><p>Agenda penutupan/check-out pukul 08.00–12.00 sesuai rundown.</p></div></article></div><section class="grid2"><article class="panel"><h2>Meeting Room 1</h2><p>Shop drawing dan RKS teknis</p><div class="actions"><div><b>A</b><p><strong>MSP</strong>Quadratura, JKON, CCM dan DPAN-GPAN1.</p><em>Day 1</em></div><div><b>B</b><p><strong>Taman Milenial</strong>Quadratura, JKON, CCM dan DPAN-GPAN1.</p><em>Day 2</em></div><div><b>C</b><p><strong>GBI</strong>Metrik, JKON, CCM dan DPAN-GPAN1.</p><em>Day 2–3</em></div></div></article><article class="panel"><h2>Meeting Room 2</h2><p>Approval material, outline specification dan long lead</p><div class="actions"><div><b>A</b><p><strong>MSP</strong>Approval material dan item pengadaan kritis.</p><em>Day 1</em></div><div><b>B</b><p><strong>Taman Milenial</strong>Approval dan long lead area taman.</p><em>Day 2</em></div><div><b>C</b><p><strong>GBI</strong>Approval sistem khusus GBI.</p><em>Day 2–3</em></div></div></article></section>`;}

function render(){const route=(location.hash||'#overview').slice(1);setNav(route);({overview,shopdrawing,material,bim,workshop}[route]||overview)();window.scrollTo(0,0);}window.addEventListener('hashchange',render);render();